server:
  port: 3000

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    database: 0
    timeout: 30000
    password: ${REDIS_PASS}
    jedis:
      pool:
        max-active: 32
        max-wait: 30000
        max-idle: 32
        min-idle: 0

jwt:
  secret: ${JWT_SECRET}
  expiration: 2592000000 # 30 days

minio:
  url: ${minio_url:http://localhost:9000}
  accessKey: ${minio_acccesskey:accessKey}
  secretKey: ${minio_serectkey:secretKey}
