server:
  port: 3000

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: 2592000000 # 30 days

minio:
  url: ${minio_url:http://localhost:9000}
  accessKey: ${minio_acccesskey:accessKey}
  secretKey: ${minio_serectkey:secretKey}
