server:
  port: 3000

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: whgwhg66666666666666666666666666
  expiration: 2592000000 # 30 days
